### ISSUE TITLE
Групова робота

### ISSUE THREAD

**Issue by Strishenets** [Strishenets/project#1]
Я випадково знесла все, тому зараз відновлюю. (ಡ‸ಡ)
Будь ласка, повторіть всю зроблену вами роботу

**Comment by tanymal** [comment]
Вчора була організована зустріч в 20:00 та обговорено план роботи

**Comment by tanymal** [comment]
Вчора було розроблено перший прототип коду, який має в собі основний функціонал

**Comment by tanymal** [comment]
Код потребує вдосконалення
Програма потребує оформлення

**Comment by Strishenets** [comment]
Ок 
Я цим займусь
ヽ(´ー` )┌
